apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reaperc2-ingress
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    # cert-manager.io/cluster-issuer: letsencrypt-staging
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/frontend-entry-points: http, https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  ingressClassName: traefik
  rules:
    - host: ai-metrics.outsystemscloud.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: reaperc2-service
                port:
                  number: 8080
  tls:
    - hosts:
        - ai-metrics.outsystemscloud.ai
      secretName: c2-reaperc2-com-tls
